./do_cmake.sh \
  -DCMAKE_C_COMPILER=/usr/bin/clang-19 \
  -DCMAKE_CXX_COMPILER=/usr/bin/clang++-19 \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=YES \
  -DWITH_PYTHON3=3.13 \
  -DWITH_QATLIB=OFF \
  -DWITH_QATZIP=OFF \
  -DWITH_RADOSGW_POSIX=OFF
